# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prueba2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from http.client import SWITCHING_PROTOCOLS
import speech_recognition as sr
import pyttsx3
from llamadaVentana import Ui_Form2
from videoVentana import VideoWindow
# Initialize the recognizer
r = sr.Recognizer()


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(539, 312)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(60, 110, 171, 61))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(150, 0, 230, 51))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 60, 541, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 190, 171, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 110, 171, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 190, 171, 61))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def SVentana(self):
        self.ventana = QtWidgets.QWidget()
        self.ui = Ui_Form2()
        self.ui.setupUi(self.ventana)
        self.ventana.show()

    def vVideo(self):
        self.v = QtWidgets.QWidget()
        self.ui = VideoWindow()
        self.ui.setupUi(self.v)
        self.v.show()

    def presionado1(self):
        self.pushButton.clicked.connect(mensaje1)

    def presionado2(self):
        self.pushButton_2.clicked.connect(mensaje2) 

    def presionado3(self):
        self.pushButton_3.clicked.connect(mensaje3) 

    def presionado4(self):
        self.pushButton_4.clicked.connect(mensaje4)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Llamar a un familiar"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Asistente virtual</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">(Versión 1)</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Selecciona o di la opción que gustes</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "Reproducir música"))
        self.pushButton_2.setText(_translate("Form", "Mostrar videos"))
        self.pushButton_4.setText(_translate("Form", "Llamar a un asistente"))

def SpeakText(command):
     
    engine = pyttsx3.init()
    voices = engine.getProperty('voices')
    engine.setProperty('voice', voices[2].id)
    engine.say(command)
    engine.runAndWait()

SpeakText("Hola")
SpeakText("¿Qué puedo hacer por tí?")
SpeakText("Selecciona o di la opción que gustes")

def mensaje1():
    SpeakText("Has seleccionado llamar a un familiar")
    ui.SVentana()
    SpeakText("Presiona el botón")
    
def mensaje2():
    SpeakText("Has seleccionado ver videos")
    ui.vVideo()

def mensaje3():
    SpeakText("Has seleccionado reproducir música")

def mensaje4():
    SpeakText("Has seleccionado llamar a un asistente")
    ui.SVentana()
    SpeakText("Presiona el botón")    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    ui.presionado1()
    ui.presionado2()
    ui.presionado3()
    ui.presionado4()
    sys.exit(app.exec_())
